# Use the official Maven image to build the application
FROM maven:3.8.6-openjdk-17-slim AS builder
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

# Use OpenJDK image to run the application
FROM openjdk:17-jdk-slim
WORKDIR /app
COPY --from=builder /app/target/roomBooker-0.0.1-SNAPSHOT.jar roomBooker.jar
ENTRYPOINT ["java", "-jar", "roomBooker.jar"]
